---
# ansible-playbook nginx_controller_agent.yaml -i loadbalancers -e "admin_email=user@company.com admin_password=userPassword" 
# ansible-playbook nginx_controller_agent_3x.yaml -e "@nginx_install_controller_vars.yaml"

- hosts: loadbalancers
  remote_user: ubuntu
  become: true
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: install minimal support for python2 for Agent install script
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - python-minimal

  # https://www.nginx.com/blog/monitoring-nginx/
  - name: COPY stub_status.conf /etc/nginx/conf.d/
    copy:
      src: "{{playbook_dir}}/stub_status.conf"
      dest: "/etc/nginx/conf.d/stub_status.conf"
      force: yes

  # necessary for process monitoring.
  - name: COPY nginx-plus-api.conf /etc/nginx/conf.d/
    copy:
      src: "{{playbook_dir}}/nginx-plus-api.conf"
      dest: "/etc/nginx/conf.d/nginx-plus-api.conf"
      force: yes

  - name: login to Controller
    uri:
      url: "https://{{fqdn}}/api/v1/platform/login"
      method: "POST"
      body: 
        credentials:
          type: "BASIC"
          username: "{{admin_email}}"
          password: "{{admin_password}}"
      body_format: json
      return_content: yes
      status_code: 204
      validate_certs: false
    register: auth

  - name: Get controller api key
    uri:
      url: "https://{{fqdn}}/api/v1/platform/global"
      method: "GET"
      return_content: yes
      status_code: 200
      validate_certs: false
      headers:
        Cookie: "{{auth.set_cookie}}"
    register: ctrl_globals

  - name: Copy auth_token to a variable
    set_fact:
      api_key: "{{ctrl_globals.json.currentStatus.agentSettings.apiKey}}"

  - name: download the installer script from controller
    get_url:
      url: "https://{{fqdn}}:8443/1.4/install/controller/"
      dest: /home/ubuntu/install.sh
      validate_certs: no
      force: yes
    register: controller_return

  - name: run the Controller Agent installer
    shell: "API_KEY={{api_key}} sh ./install.sh"
    args:
      chdir: /home/ubuntu
    register: agent_install

  - debug:
      var: agent_install.stdout_lines

  - name: restart nginx
    service:
      name=nginx
      state=restarted
