# ansible-playbook nginx_controller_certificate.yaml -e "user_email=brian@itproctology.com user_password=36x4esg8 controller_fqdn=ip-10-1-10-25.us-east-2.compute.internal" 
# ansible-playbook nginx_controller_certificate.yaml -e "@nginx_install_controller_vars.yaml"

- hosts: localhost
  gather_facts: no

  tasks:
  - include_role:
      name: ansible-role-nginx-controller-generate-token

  - name: create the certificate object
    include_role:
      name: ansible-role-nginx-controller-certificate
    vars:
      environmentName: "production-us-west"
      certificate:
        metadata:
          name:  "star.acmefinancial.net"
          displayName:  "Root WWW Cert"
          description:  "A complete sentence description to that not useful."
        desiredState:
          type:  PEM
          privateKey: |-
            -----BEGIN RSA PRIVATE KEY-----
            MIIEowIBAAKCAQEAtx3/EZcYRGGb1VAzLf0dWIZ4VwhkoXIQrvEaPt6uWQgJ5gHo
            q7W8dK2VhFIauQEmEl9Cjky6p95X6kbZFF8uVv0FgOZ7svj4GIFbdHon3RZO4CWm
                                     ---snip---
            uRd9M41syfkkukK7fmTEz2OKgJbEeBiCf8zLM/vmRi1cn1Z6QIC4Kgo34PgpDNoS
            n5QVeWmfV70OnPzbVcSQUgMyubmDhsaK/U7sfglJ6q685sf9Fp1C
            -----END RSA PRIVATE KEY-----
          publicCert: |-
            -----BEGIN CERTIFICATE-----
            MIIDzDCCArSgAwIBAgIBCzANBgkqhkiG9w0BAQsFADCBjDELMAkGA1UEBhMCVVMx
            EzARBgNVBAgMCldhc2hpbmd0b24xFzAVBgNVBAoMDkFjbWUgRmluYW5jaWFsMScw
                                     ---snip---
            mlYfOifrR26bg9t0vDqMtw+FYHPp/xtCkvzXhQdSY7yE7WfgtatTaL62fy7BTJ2x
            7DvkVHeczMkGWs+YOJ0wXQ==
            -----END CERTIFICATE-----
          caCerts:
            - |-
              -----BEGIN CERTIFICATE-----
              MIID3DCCAsSgAwIBAgIBADANBgkqhkiG9w0BAQsFADBuMQswCQYDVQQGEwJVUzET
              MBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEXMBUGA1UECgwO
                                     ---snip---
              tJoecATzX7TwBo0fXric9U5Urtn9vZ8YcyCnj3MUf3uchov2m9/0zSd5NGS++Gd8
              yS44L0W07g9gY/L6tRz7FoQxGuLmdTqAef/JFlRvZsI=
              -----END CERTIFICATE-----
            - |-
              -----BEGIN CERTIFICATE-----
              MIIDwjCCAqqgAwIBAgIJAK3BVO5QXatDMA0GCSqGSIb3DQEBCwUAMG4xCzAJBgNV
              BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRcw
                                     ---snip---
              8SBk+TgaFnaqn8j1MwjeAKzakfkwxfoVhcTvHiVUUYXcGZJnJwKJuoNfF5MLMyQC
              I+6MfrCB
              -----END CERTIFICATE-----
