---
# ansible-playbook nginx_controller_agent.yaml -i loadbalancers -e "admin_email=user@company.com admin_password=userPassword" 
# ansible-playbook nginx_controller_agent_3x.yaml -e "@nginx_install_controller_vars.yaml"

- hosts: loadbalancers
  remote_user: ubuntu
  become: true
  become_method: sudo
  gather_facts: yes

  tasks:
  # - name: upgrade packages here.
  #   apt:
  #     update_cache: yes
  #     upgrade: yes

  - name: install minimal support for python2 for Agent install script
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python-minimal

  - include_role:
      # name: nginxinc.nginx-controller-generate-token
      name: ansible-role-nginx-controller-generate-token
    # vars:
    #   user_email: "user@example.com"
    #   user_password: 'secure_password'
    #   controller_fqdn: ""

  - name: Get controller api key for agent registration
    uri:
      url: "https://{{controller_fqdn}}/api/v1/platform/global"
      method: "GET"
      return_content: yes
      status_code: 200
      validate_certs: false
      headers:
        Cookie: "{{controller_auth_token}}"
    register: ctrl_globals

  - name: Copy api_key to a variable
    set_fact:
      api_key: "{{ctrl_globals.json.currentStatus.agentSettings.apiKey}}"

  - name: install the agent
    include_role:
      # name: nginxinc.nginx-controller-agent
      name: ansible-role-nginx-controller-agent
    # vars:
    #   controller_fqdn:
    #   api_key:
