# ansible-playbook nginx_controller_gateway.yaml -e "user_email=brian@itproctology.com user_password=36x4esg8 controller_fqdn=ip-10-1-10-25.us-east-2.compute.internal" 
# ansible-playbook nginx_controller_gateway.yaml -e "@nginx_install_controller_vars.yaml"

- hosts: localhost
  gather_facts: no

  tasks:
  - include_role:
      name: ansible-role-nginx-controller-generate-token

  - name: configure the gateway
    include_role:
      name: ansible-role-nginx-controller-gateway
    vars:
      environment_name: "production-us-west"
      gateway:
        name: lending
        displayName: "Shared Public Lending BU Gateway"
        description: "Routes all non special Lending applications"
      ingress:
        uris:
        - "http://mortgage.acmefinancial.net"
        - "https://mortgage.acmefinancial.net"
        - "http://ratecalculator.acmefinancial.net"
        - "https://ratecalculator.acmefinancial.net"
        tls:
          certRef:
            ref: "/services/environments/production-us-west/certs/star.acmefinancial.net"
          protocols:
          - "TLSv1.3"
          - "TLSv1.2"
        placement:
          instanceRefs:
          - "/infrastructure/locations/unspecified/instances/6"
