---
## retreive dynamic settings information at the Ansible Controller
## on the remote host
- hosts: appcontainers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
  # add the docker repo
  - name: Import docker CE repository key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add Docker ce repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present

  - name: update the apt cache
    apt: 
      update_cache: yes

  - name: list versions available
    shell: apt-cache show docker-ce
    register: docker_versions

  - name: install docker community edition
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce

  - name: setup docker daemon
    copy:
      src: "{{playbook_dir}}/docker_daemon.json"
      dest: /etc/docker/daemon.json

  # https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    # when: ansible_swaptotal_mb > 0

  - name: restart docker daemon
    service: 
      name: docker
      state: restarted
