---
# ansible-playbook nginx_controller_users.yaml -i controller -e "controller_user_email=user@company.com controller_password=userPassword" 
# add users to nginx Controller
- hosts: localhost

  tasks:
  - name: get controller internal DNS, written to inventory file
    shell: cat "{{playbook_dir}}/controller"
    register: controller

  - name: set the controller private fqdn
    set_fact:
      controller_dns: "{{controller.stdout_lines[1]}}"

  - debug:
      var: controller_dns

- hosts: controller
  remote_user: ubuntu
  become: true
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: login to Controller
    uri:
      url: "https://{{hostvars['localhost']['controller_dns']}}/api/v1/platform/login"
      method: "POST"
      body: 
        credentials:
          type: "BASIC"
          username: "{{controller_user_email}}"
          password: "{{controller_password}}"
      body_format: json
      return_content: yes
      status_code: 204
      validate_certs: false
    register: auth

  - name: POST controller license
    uri:
      url: "https://{{hostvars['localhost']['controller_dns']}}/api/v1/platform/license-file"
      method: POST
      body: 
        content: "{{ license }}"
      body_format: json
      return_content: yes
      status_code: 200
      validate_certs: false
      headers:
        Cookie: "{{auth.set_cookie}}"
    register: controller_response

  - name: GET controller license status
    uri:
      url: "https://{{hostvars['localhost']['controller_dns']}}/api/v1/platform/license"
      method: GET
      status_code: 200
      validate_certs: false
      headers:
        Cookie: "{{auth.set_cookie}}"
    register: controller_license

